services:
  servicebuswebclient:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - .env
    networks:
      sb-emulator:
        aliases:
          - "sb-emulator"

networks:
  sb-emulator: